
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NL"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono NL"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono NL"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
blur = true
decorations = "none"
opacity = 0.9
startup_mode="Fullscreen"

[window.padding]
x = 3
y = 3

[general]
live_config_reload = true

[cursor]
blink_interval=600
unfocused_hollow=true

[cursor.style]
shape="Block"
blinking="On"

[mouse]
hide_when_typing=false
